<a href="https://colab.research.google.com/github/chengleniubi/tensorfolw_note/blob/main/01_tensor%E5%B8%B8%E9%87%8F%E5%8F%98%E9%87%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

# 张量的基础操作

In [ ]:
# 创建0维张量
tf.constant(3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
# 创建1维张量
tf.constant([1.0,2.0,3.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
# 创建2维张量
tf.constant([[1, 2],
      [3, 4],
      [5, 6]
      ], dtype=tf.float16)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [ ]:
# 创建3维张量
tf.constant([
      [[1, 2, 3, 4, 5],
      [2, 3, 4, 5, 6]],
      [[1, 2, 3, 4, 5],
      [2, 3, 4, 5, 6]]
      ], dtype=tf.float64)

<tf.Tensor: shape=(2, 2, 5), dtype=float64, numpy=
array([[[1., 2., 3., 4., 5.],
        [2., 3., 4., 5., 6.]],

       [[1., 2., 3., 4., 5.],
        [2., 3., 4., 5., 6.]]])>

# 转换成numpy

In [ ]:
tensor1 = tf.constant([1,2,3,4,5])

In [ ]:
tensor1

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [ ]:
np.array(tensor1)

array([1, 2, 3, 4, 5], dtype=int32)

In [ ]:
tensor1.numpy()

array([1, 2, 3, 4, 5], dtype=int32)

# 常用函数

In [ ]:
a = tf.constant([[1.0, 2],
          [3, 4]])

In [ ]:
b = tf.constant([[1.0, 1],[1, 1]])

In [ ]:
a[0,0]=1

In [ ]:
# 加法
tf.add(a,b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [ ]:
# 元素相乘
tf.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
# 矩阵乘法
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [7., 7.]], dtype=float32)>

In [ ]:
# 最大值
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [ ]:
# 最大值索引
tf.argmax(a)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [ ]:
# 平均值
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

# 变量

In [ ]:
var = tf.Variable([[1,2],[3,4]])

In [ ]:
var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
var.shape

TensorShape([2, 2])

In [ ]:
var.dtype

tf.int32

In [ ]:
var.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [ ]:
var.assign([[2,3],[4,5]])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
var.assign([2,3])

ValueError: ignored

In [ ]:
var[0,0]=1

TypeError: ignored