<a href="https://colab.research.google.com/github/chengleniubi/tensorfolw_note/blob/main/01_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

# 张量的基础操作

In [2]:
# 创建0维张量
tf.constant(3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [3]:
# 创建1维张量
tf.constant([1.0,2.0,3.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [4]:
# 创建2维张量
tf.constant([[1, 2],
      [3, 4],
      [5, 6]
      ], dtype=tf.float16)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [5]:
# 创建3维张量
tf.constant([
      [[1, 2, 3, 4, 5],
      [2, 3, 4, 5, 6]],
      [[1, 2, 3, 4, 5],
      [2, 3, 4, 5, 6]]
      ], dtype=tf.float64)

<tf.Tensor: shape=(2, 2, 5), dtype=float64, numpy=
array([[[1., 2., 3., 4., 5.],
        [2., 3., 4., 5., 6.]],

       [[1., 2., 3., 4., 5.],
        [2., 3., 4., 5., 6.]]])>

# 转换成numpy

In [6]:
tensor1 = tf.constant([1,2,3,4,5])

In [7]:
tensor1

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [8]:
np.array(tensor1)

array([1, 2, 3, 4, 5], dtype=int32)

In [9]:
tensor1.numpy()

array([1, 2, 3, 4, 5], dtype=int32)

# 常用函数

In [10]:
a = tf.constant([[1.0, 2],
          [3, 4]])

In [11]:
b = tf.constant([[1.0, 1],[1, 1]])

In [12]:
a[0,0]=1
# 常量不能赋值

TypeError: ignored

In [13]:
# 加法
tf.add(a,b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [14]:
# 元素相乘
tf.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [16]:
# 矩阵乘法
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [7., 7.]], dtype=float32)>

In [17]:
# 最大值
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [18]:
# 最大值索引
tf.argmax(a)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [19]:
# 平均值
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

# 变量

In [20]:
var = tf.Variable([[1,2],[3,4]])

In [21]:
var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [22]:
var.shape

TensorShape([2, 2])

In [23]:
var.dtype

tf.int32

In [24]:
var.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [25]:
var.assign([[2,3],[4,5]])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [26]:
var.assign([2,3])
# 思考错在哪？
# 下面也是

ValueError: ignored

In [27]:
var[0,0]=1


TypeError: ignored